wow

diff --git a/.github/workflows/snyk.yml b/.github/workflows/snyk.yml
--- a/.github/workflows/snyk.yml
+++ b/.github/workflows/snyk.yml
@@ -6,29 +6,25 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@master
-
-      - name: Install Snyk
-        run: npm install -g snyk
-
       - name: Run Snyk to check for vulnerabilities
-        # Using the CLI directly ensures the SARIF file is created in the current workspace
-        run: snyk test --sarif-file-output=snyk.sarif
-        continue-on-error: true
+        uses: snyk/actions/python@master
+        continue-on-error: true # To make sure that SARIF upload gets called
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-
+        with:
+          command: code test
+          args: --sarif-file-output=snyk.sarif
+          
       - name: Count total number of vulnerabilities
         run: |
-          # The file snyk.sarif will now exist in the root directory
           RESULTS_LENGTH=$(jq '.runs[0].results | length' snyk.sarif)
           echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
-          echo "Total Vulnerabilities: $RESULTS_LENGTH"
-
+          echo $RESULTS_LENGTH
       - name: Pass_or_Fail_the_job
         run: |
-          if [ "$RESULTS_LENGTH" != "0" ]; then
-            echo "Job Failed due to $RESULTS_LENGTH vulnerabilities."
-            exit 1
-          else
-            echo "Pass: No vulnerabilities found."
-          fi
+            if [ "$RESULTS_LENGTH" != 0 ]; then
+                echo "Job Failed"
+                exit 1
+            else
+                echo "Pass"
+            fi
